<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
	<OutputType>Library</OutputType>
	<IsPackable>false</IsPackable>
    <!--<ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PlatformTarget>AnyCPU</PlatformTarget>-->
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Moq" Version="4.18.4" />
	<PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <!--<PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseWork\CourseWork.csproj" />
  </ItemGroup>

  <!--<ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>-->

</Project>
